=== polijicCes3/06-Ejercicio/Ejercicio-06.dtd
<!ELEMENT listacursos (curso+)>
<!ELEMENT curso (alumno+)>
<!ELEMENT alumno (DNI,primernombre,segundonombre*,primerapellido,segundoapellido*)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT primernombre (#PCDATA)>
<!ELEMENT segundonombre (#PCDATA)>
<!ELEMENT primerapellido (#PCDATA)>
<!ELEMENT segundoapellido (#PCDATA)>
<!ELEMENT asignaturas (asignatura+)>
<!ELEMENT asignatura (codigo,nombre,profesor)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT profesor (NRP,primernombre,segundonombre*,primerapellido,segundoapellido*)>
<!ELEMENT NRP (#PCDATA)>

=== polijicCes3/06-Ejercicio/Ejercicio-06.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM "Ejercicio-06.dtd">
<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio-06.xsd">
    <curso>
        <alumno>
            <DNI>1010640462</DNI>
            <primernombre>Cristian</primernombre>
            <primerapellido>Grisales</primerapellido>
            <segundoapellido>Venitez</segundoapellido>
            <asignaturas>
                <asignatura>
                    <codigo>1</codigo>
                    <nombre>Laravel II</nombre>
                    <profesor>
                        <NRP>99000</NRP>
                        <primernombre>Fernando</primernombre>
                        <primerapellido>Herrera</primerapellido>
                    </profesor>
                </asignatura>
                <asignatura>
                    <codigo>2</codigo>
                    <nombre>React</nombre>
                    <profesor>
                        <NRP>99001</NRP>
                        <primernombre>Ubaldo</primernombre>
                        <primerapellido>Acosta</primerapellido>
                    </profesor>
                </asignatura>
            </asignaturas>
        </alumno>

        <alumno>
            <DNI>1001360499</DNI>
            <primernombre>Dayana</primernombre>
            <primerapellido>Gomez</primerapellido>
            <segundoapellido>Moreno</segundoapellido>
            <asignaturas>
                <asignatura>
                    <codigo>1</codigo>
                    <nombre>Ingles II</nombre>
                    <profesor>
                        <NRP>25782</NRP>
                        <primernombre>Sol</primernombre>
                        <primerapellido>Mirella</primerapellido>
                    </profesor>
                </asignatura>
                <asignatura>
                    <codigo>2</codigo>
                    <nombre>Derecho societario</nombre>
                    <profesor>
                        <NRP>2</NRP>
                        <primernombre>Juan</primernombre>
                        <segundonombre>Fernando</segundonombre>
                        <primerapellido>Buitrago</primerapellido>
                    </profesor>
                </asignatura>
            </asignaturas>
        </alumno>
    </curso>
</listacursos>
